preferred_syntax = :scss
http_path = '/'
css_dir = 'assets/css/'
sass_dir = 'assets/sass/'
images_dir = 'assets/images'
javascripts_dir = 'assets/javascript'
relative_assets = true
line_comments = true
# output_style = :compressed